# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/forest/gitreps/labs-trubnikov/hw-02_huffman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/forest/gitreps/labs-trubnikov/hw-02_huffman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/forest/gitreps/labs-trubnikov/hw-02_huffman/CMakeFiles /home/forest/gitreps/labs-trubnikov/hw-02_huffman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/forest/gitreps/labs-trubnikov/hw-02_huffman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hw-02_huffman_test

# Build rule for target.
hw-02_huffman_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw-02_huffman_test
.PHONY : hw-02_huffman_test

# fast build rule for target.
hw-02_huffman_test/fast:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/build
.PHONY : hw-02_huffman_test/fast

#=============================================================================
# Target rules for targets named hw-02_huffman

# Build rule for target.
hw-02_huffman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw-02_huffman
.PHONY : hw-02_huffman

# fast build rule for target.
hw-02_huffman/fast:
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/build
.PHONY : hw-02_huffman/fast

src/archive.o: src/archive.cpp.o

.PHONY : src/archive.o

# target to build an object file
src/archive.cpp.o:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/archive.cpp.o
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/archive.cpp.o
.PHONY : src/archive.cpp.o

src/archive.i: src/archive.cpp.i

.PHONY : src/archive.i

# target to preprocess a source file
src/archive.cpp.i:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/archive.cpp.i
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/archive.cpp.i
.PHONY : src/archive.cpp.i

src/archive.s: src/archive.cpp.s

.PHONY : src/archive.s

# target to generate assembly for a file
src/archive.cpp.s:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/archive.cpp.s
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/archive.cpp.s
.PHONY : src/archive.cpp.s

src/boolio.o: src/boolio.cpp.o

.PHONY : src/boolio.o

# target to build an object file
src/boolio.cpp.o:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/boolio.cpp.o
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/boolio.cpp.o
.PHONY : src/boolio.cpp.o

src/boolio.i: src/boolio.cpp.i

.PHONY : src/boolio.i

# target to preprocess a source file
src/boolio.cpp.i:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/boolio.cpp.i
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/boolio.cpp.i
.PHONY : src/boolio.cpp.i

src/boolio.s: src/boolio.cpp.s

.PHONY : src/boolio.s

# target to generate assembly for a file
src/boolio.cpp.s:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/boolio.cpp.s
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/boolio.cpp.s
.PHONY : src/boolio.cpp.s

src/decoder.o: src/decoder.cpp.o

.PHONY : src/decoder.o

# target to build an object file
src/decoder.cpp.o:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/decoder.cpp.o
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/decoder.cpp.o
.PHONY : src/decoder.cpp.o

src/decoder.i: src/decoder.cpp.i

.PHONY : src/decoder.i

# target to preprocess a source file
src/decoder.cpp.i:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/decoder.cpp.i
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/decoder.cpp.i
.PHONY : src/decoder.cpp.i

src/decoder.s: src/decoder.cpp.s

.PHONY : src/decoder.s

# target to generate assembly for a file
src/decoder.cpp.s:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/decoder.cpp.s
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/decoder.cpp.s
.PHONY : src/decoder.cpp.s

src/encoder.o: src/encoder.cpp.o

.PHONY : src/encoder.o

# target to build an object file
src/encoder.cpp.o:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/encoder.cpp.o
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/encoder.cpp.o
.PHONY : src/encoder.cpp.o

src/encoder.i: src/encoder.cpp.i

.PHONY : src/encoder.i

# target to preprocess a source file
src/encoder.cpp.i:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/encoder.cpp.i
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/encoder.cpp.i
.PHONY : src/encoder.cpp.i

src/encoder.s: src/encoder.cpp.s

.PHONY : src/encoder.s

# target to generate assembly for a file
src/encoder.cpp.s:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/encoder.cpp.s
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/encoder.cpp.s
.PHONY : src/encoder.cpp.s

src/flags.o: src/flags.cpp.o

.PHONY : src/flags.o

# target to build an object file
src/flags.cpp.o:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/flags.cpp.o
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/flags.cpp.o
.PHONY : src/flags.cpp.o

src/flags.i: src/flags.cpp.i

.PHONY : src/flags.i

# target to preprocess a source file
src/flags.cpp.i:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/flags.cpp.i
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/flags.cpp.i
.PHONY : src/flags.cpp.i

src/flags.s: src/flags.cpp.s

.PHONY : src/flags.s

# target to generate assembly for a file
src/flags.cpp.s:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/flags.cpp.s
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/flags.cpp.s
.PHONY : src/flags.cpp.s

src/huffman.o: src/huffman.cpp.o

.PHONY : src/huffman.o

# target to build an object file
src/huffman.cpp.o:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/huffman.cpp.o
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/huffman.cpp.o
.PHONY : src/huffman.cpp.o

src/huffman.i: src/huffman.cpp.i

.PHONY : src/huffman.i

# target to preprocess a source file
src/huffman.cpp.i:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/huffman.cpp.i
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/huffman.cpp.i
.PHONY : src/huffman.cpp.i

src/huffman.s: src/huffman.cpp.s

.PHONY : src/huffman.s

# target to generate assembly for a file
src/huffman.cpp.s:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/src/huffman.cpp.s
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/huffman.cpp.s
.PHONY : src/huffman.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/hw-02_huffman.dir/build.make CMakeFiles/hw-02_huffman.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/boolio_test.o: test/boolio_test.cpp.o

.PHONY : test/boolio_test.o

# target to build an object file
test/boolio_test.cpp.o:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/boolio_test.cpp.o
.PHONY : test/boolio_test.cpp.o

test/boolio_test.i: test/boolio_test.cpp.i

.PHONY : test/boolio_test.i

# target to preprocess a source file
test/boolio_test.cpp.i:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/boolio_test.cpp.i
.PHONY : test/boolio_test.cpp.i

test/boolio_test.s: test/boolio_test.cpp.s

.PHONY : test/boolio_test.s

# target to generate assembly for a file
test/boolio_test.cpp.s:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/boolio_test.cpp.s
.PHONY : test/boolio_test.cpp.s

test/decoder_test.o: test/decoder_test.cpp.o

.PHONY : test/decoder_test.o

# target to build an object file
test/decoder_test.cpp.o:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/decoder_test.cpp.o
.PHONY : test/decoder_test.cpp.o

test/decoder_test.i: test/decoder_test.cpp.i

.PHONY : test/decoder_test.i

# target to preprocess a source file
test/decoder_test.cpp.i:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/decoder_test.cpp.i
.PHONY : test/decoder_test.cpp.i

test/decoder_test.s: test/decoder_test.cpp.s

.PHONY : test/decoder_test.s

# target to generate assembly for a file
test/decoder_test.cpp.s:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/decoder_test.cpp.s
.PHONY : test/decoder_test.cpp.s

test/encoder_test.o: test/encoder_test.cpp.o

.PHONY : test/encoder_test.o

# target to build an object file
test/encoder_test.cpp.o:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/encoder_test.cpp.o
.PHONY : test/encoder_test.cpp.o

test/encoder_test.i: test/encoder_test.cpp.i

.PHONY : test/encoder_test.i

# target to preprocess a source file
test/encoder_test.cpp.i:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/encoder_test.cpp.i
.PHONY : test/encoder_test.cpp.i

test/encoder_test.s: test/encoder_test.cpp.s

.PHONY : test/encoder_test.s

# target to generate assembly for a file
test/encoder_test.cpp.s:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/encoder_test.cpp.s
.PHONY : test/encoder_test.cpp.s

test/flags_test.o: test/flags_test.cpp.o

.PHONY : test/flags_test.o

# target to build an object file
test/flags_test.cpp.o:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/flags_test.cpp.o
.PHONY : test/flags_test.cpp.o

test/flags_test.i: test/flags_test.cpp.i

.PHONY : test/flags_test.i

# target to preprocess a source file
test/flags_test.cpp.i:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/flags_test.cpp.i
.PHONY : test/flags_test.cpp.i

test/flags_test.s: test/flags_test.cpp.s

.PHONY : test/flags_test.s

# target to generate assembly for a file
test/flags_test.cpp.s:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/flags_test.cpp.s
.PHONY : test/flags_test.cpp.s

test/huffman_test.o: test/huffman_test.cpp.o

.PHONY : test/huffman_test.o

# target to build an object file
test/huffman_test.cpp.o:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/huffman_test.cpp.o
.PHONY : test/huffman_test.cpp.o

test/huffman_test.i: test/huffman_test.cpp.i

.PHONY : test/huffman_test.i

# target to preprocess a source file
test/huffman_test.cpp.i:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/huffman_test.cpp.i
.PHONY : test/huffman_test.cpp.i

test/huffman_test.s: test/huffman_test.cpp.s

.PHONY : test/huffman_test.s

# target to generate assembly for a file
test/huffman_test.cpp.s:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/huffman_test.cpp.s
.PHONY : test/huffman_test.cpp.s

test/test.o: test/test.cpp.o

.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/hw-02_huffman_test.dir/build.make CMakeFiles/hw-02_huffman_test.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hw-02_huffman_test"
	@echo "... hw-02_huffman"
	@echo "... src/archive.o"
	@echo "... src/archive.i"
	@echo "... src/archive.s"
	@echo "... src/boolio.o"
	@echo "... src/boolio.i"
	@echo "... src/boolio.s"
	@echo "... src/decoder.o"
	@echo "... src/decoder.i"
	@echo "... src/decoder.s"
	@echo "... src/encoder.o"
	@echo "... src/encoder.i"
	@echo "... src/encoder.s"
	@echo "... src/flags.o"
	@echo "... src/flags.i"
	@echo "... src/flags.s"
	@echo "... src/huffman.o"
	@echo "... src/huffman.i"
	@echo "... src/huffman.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/boolio_test.o"
	@echo "... test/boolio_test.i"
	@echo "... test/boolio_test.s"
	@echo "... test/decoder_test.o"
	@echo "... test/decoder_test.i"
	@echo "... test/decoder_test.s"
	@echo "... test/encoder_test.o"
	@echo "... test/encoder_test.i"
	@echo "... test/encoder_test.s"
	@echo "... test/flags_test.o"
	@echo "... test/flags_test.i"
	@echo "... test/flags_test.s"
	@echo "... test/huffman_test.o"
	@echo "... test/huffman_test.i"
	@echo "... test/huffman_test.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

